services:
  # Kontener PHP
  app:
    image: php:8.5-fpm
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    env_file:
      - ../.env
    environment:
      - TMPDIR=/var/www/storage/app/tmp
      - TEMP=/var/www/storage/app/tmp
      - TZ=Europe/Warsaw
    volumes:
      - ../:/var/www
    build:
      context: ../
      dockerfile_inline: |
        FROM php:8.5-fpm
        RUN apt-get update && apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev zip git unzip tzdata \
            && ln -snf /usr/share/zoneinfo/Europe/Warsaw /etc/localtime && echo "Europe/Warsaw" > /etc/timezone \
            && docker-php-ext-configure gd --with-freetype --with-jpeg \
            && docker-php-ext-install pdo_mysql gd
        RUN echo "date.timezone=Europe/Warsaw" > /usr/local/etc/php/conf.d/timezone.ini
        COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
  # Kontener Nginx
  web:
    container_name: laravel-web
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - ../.env
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - ../:/var/www
      - ./nginx/laravel.conf:/etc/nginx/conf.d/default.conf
    build:
      context: ../
      dockerfile_inline: |
        FROM nginx:alpine
        RUN apk add --no-cache tzdata \
            && ln -snf /usr/share/zoneinfo/Europe/Warsaw /etc/localtime && echo "Europe/Warsaw" > /etc/timezone
    depends_on:
      - app

  # Kontener MySQL
  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      - TZ=Europe/Warsaw
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: